### PR TITLE
Danish locales 9.02

### PR DESCRIPTION
**Pull request by helmuthm**
Should be finished now :-)

### CODE REVIEW

**Comment by Ardakilic** [comment]
Hey @helmuthm , thanks for the translations 🎉

**Comment by helmuthm** [comment]
I just saw that I've placed most of the files in the wrong folder structure - how do I fix that?

sorry, I'm not an github wizard ... and it was late and I was tired and so on and so on ;-)

**Comment by Domi-php** [comment]
Np, removed for reupload !

**Comment by Ardakilic** [comment]
Offtopic: here's an alternative trick for automatic revert: 

image

**Comment by helmuthm** [comment]
([http://www.php-fusion.co.uk/forum/viewthread.php?thread_id=38454&pid=202122#post_202122])

**Comment by Ardakilic** [comment]
@helmuthm Pull request is a step to contribute a repository. You "fork" the repository  (make a clone on your account on github), and then clone it to your local computer, just like svn. Then, you make the changes in your local copy in computer, and then push them to your fork. Finally, to merge the changes you've done, create a "pull request" (a request to merge your changes into the original repository which you've forked from) from "your fork" to the source one (which in this case is here).

To add a folder in GitHub, easiest way I can think of is to clone/download your fork to your pc, make changes, and then push back to the github server. Then you can make the pull request.

I suggest you install GitHub for Windows/Mac/Whatever, it's interface is friendlier.

**Comment by Ardakilic** [comment]
@helmuthm 

To add a folder in GitHub, easiest way I can think of is to clone/download your fork to your pc, make changes, and then push back to the github server. Then you can make the pull request.

I suggest you install GitHub for Windows/Mac/Whatever, it's interface is friendlier.


However, I can see https://github.com/php-fusion/PHP-Fusion-9-Locale/tree/master/Danish folder is there.

**Pull request merged**
